const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const EDIT_TODO = "EDIT_TODO";
const MARK_TODO = "MARK_TODO";
const MARK_ALL = "MARK_TODO";
const CLEAR_MARKED = "CLEAR_MARKED";
export {
    ADD_TODO, DELETE_TODO, EDIT_TODO, MARK_TODO, MARK_ALL, CLEAR_MARKED
}